### ISSUE TITLE
Please add option to set the buffer string manually

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#1]
Currently, it is only possible to set the buffer to "CellCarrier", "CellCarrierB", and .... and "other". It would be helpful to also set the buffer to a user-defined string.

The "other" option is too general for some applications. Even if the Young's modulus cannot be computed for a particular buffer, this information is still useful for several studies.

There is the option in QtDesigner to allow manual editing of a string in a QComboBox. I believe this would be the simplest solution.

**Comment by phidahl** [comment]
This issue is scheduled and will be adressed in the next release. For calculation of Youngs's modulus a viscosity would be necessary as well?

**Comment by paulmueller** [comment]
Thanks! 

I think viscosities are a moving target, so I would not put any user-defined values in .rtdc files for now. If users request it, then this could be discussed (in a separate issue).

**Comment by phidahl** [comment]
This feature is included in ShapeIn 2.2.1.0.
