### ISSUE TITLE
Remember live-plot settings (during measurement)

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#10]
Users sometimes have preferred live-plotting settings (e.g. time vs event index to detect blockage), but Shape-In does not remember these. It would be nice if there would be an option to remember the live visualization settings.

**Comment by phidahl** [comment]
Plot settings are part of configuration files (.ini) and restored when they are loaded, since the flexible plotting system was introduced.
