### ISSUE TITLE
Shape-In crashes when sample folder was deleted

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#12]
Shape-In 2.3.3.54

I did a measurement, close Shape-In, delete the folder from that measurement, then restart Shape-In again, I see Shape-In opening and showing a error message telling me that the path to the sample folder is invalid ("Storage/Sample location error"), then Shape-In crashes. If I manage to click on "ok" in the window with the error message within the 3-4 s time frame it's visible, Shape-In does not crash. I guess Shape-In connects to the pumps and the camera first and then checks the sample folder, that's why there are a few seconds between starting the Shape-In and the crashing of it.

**Comment by phidahl** [comment]
Thanks for reporting. We could reproduce the issue and will fix it with the next release.
