### ISSUE TITLE
Shape-In sometimes just stops the measurement

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#13]
Shape-In 2.3.3.54

Sometimes, the measurement just stops without a warning or error message. It either doesn't show an image anymore or sometimes shows the image of the last event that was detected. The button in the top left still shows "Stop measurement", but it's not measuring anymore.

The connection between Shape-In and the camera was unstable in the past, showing the "no images from camera received" error. This doesn't happen anymore, but could be related, based on previous experience how often the problem occurred.

**Comment by phidahl** [comment]
Most likely hardware problem
