### ISSUE TITLE
Enhancement: Warnings for low syringe filling level and low disk space

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#14]
I think it would be useful to show a warning if a user wants to start a measurement and the syringes contain less than, for example, 50 µl buffer and if the available disk space is less than, say, 40 GB. These limits could maybe also be adjusted in the settings according to ones needs.

It could ask the user if the measurement should be started anyway or not, and in the latter case, the user could refill the syringes or free up disk space.

**Comment by phidahl** [comment]
Thanks for this proposal. It will be considered for the next release.
