### ISSUE TITLE
Shape-In creates broken RTDC files when using fluorescence and the lid is not closed (abort by interlock)

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#15]
Shape-In 2.3.3.54

When doing measurements with fluorescence, the device starts a measurement only if the interlocks are both ok to prevent laser radiation to come out of the device. If one forgets the lid and presses "Start measurement", an rtdc file is created but with no content or only with some meta data header.  
But trying to open the file with DCKit or Shape-Out, one will get an error. The file doesn't contain any data anyway, so I propose that the file is not generated at all in case the measurement is aborted before detecting the first event or Shape-In automatically deletes it, if no event is stored in there.

**Comment by phidahl** [comment]
Thanks for reporting.
This behaviour is unexpected. We will fix it with the next release.
As a workaround you'll have to delete these empty files by hand.
