### ISSUE TITLE
Laser count inconsistent

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#2]
ShapeOut2 shows "Number of active lasers = 0" although the measurement was done with two active lasers. 
The according error from DCKit is "Metadata: fluorescence laser count inconsistent".
It seems that the number of active lasers is not stored correctly in the .rtdc file.

ShapeIn 2.2.2.1
ShapeOut 2.6
DCKit 0.12.4

**Comment by paulmueller** [comment]
Do you have an exemplary raw data file somewhere?

**Comment by B-Hartmann** [comment]
[example_data.zip](https://github.com/ZELLMECHANIK-DRESDEN/ShapeIn_Issues/files/6162799/example_data.zip)

**Comment by paulmueller** [comment]
This is what HDFView gives me for that file:
![image](https://user-images.githubusercontent.com/2853022/111604247-71aed880-87d5-11eb-87fb-05859724c674.png)

@phidahl looks like Shape-In did not store the `laser count`?

**Comment by phidahl** [comment]
This was fixed in Version 2.2.2.4 which will be released today.
