### ISSUE TITLE
CellCarrierB written to .hdf5 file although CellCarrier selected in GUI

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#3]
Shape-In 2.2.2.1 does not correctly store the medium in the .hdf5 file. When "CellCarrier" is selectedm "CellCarrierB" is written to the file.

Shape-In:
![image](https://user-images.githubusercontent.com/2853022/111607914-fbac7080-87d8-11eb-9a81-e67bdde2d037.png)

HDFView:
![image](https://user-images.githubusercontent.com/2853022/111608111-28f91e80-87d9-11eb-9d1d-bf7309ebebda.png)

SoftwareSettings.ini says
```
[SampleProp]
Buffer_Medium=CellCarrierB
```

@phidahl Can you reproduce this?

**Comment by phidahl** [comment]
Yes, this is already fixed in current development branch. We will release ASAP

**Comment by phidahl** [comment]
It must be related to the possibility to add own medium names introduced before

**Comment by paulmueller** [comment]
I suppose it would make sense to allow people to change the medium in DCKit if the file was generated by a specific version of Shape-In.

- Which versions of Shape-In are affected? 
- How does the bug work? Is "CellCarrierB" always written or is it only written when "CellCarrier" is selected?

**Comment by phidahl** [comment]
Versions affected: from 2.2.1.0 
Will be fixed in Version 2.2.3.0

The problem only affects selection of "CellCarrier" which has index 0. Any other media with index >0 can be selected and will be updated.

There is a possibility to rescue the value without user interaction:
In the ini file there is
"SampleProp/Buffer_Medium_ID" which is correct. If this =0 the Buffer_Medium string should be "CellCarrier"

**Comment by phidahl** [comment]
Correction: It is already fixed in Version 2.2.2.3

**Comment by paulmueller** [comment]
How many versions of Shape-In were there with the prefix "2.2.1.x"? Shape-In does not follow semantic versioning so I have not easy way of comparing versions. My current approach is to check whether the version is in the list `["2.2.1.0", "2.2.1.1", ..., "2.2.2.0", "2.2.2.1", "2.2.2.2", "2.2.2.3"]`.

**Comment by phidahl** [comment]
Versions affected are: 
- 2.2.1.0
- 2.2.2.0
- 2.2.2.1
- 2.2.2.2

**Comment by phidahl** [comment]
There might be Versions with a suffix: "2.2.1.0dev". Can you ignore the suffix?

**Comment by paulmueller** [comment]
Users are now notified in DCKit (Integrity check) / dclab-verify-dataset and DCKit can automatically correct the buffer using SoftwareSettings.ini. Since this is already fixed in Shape-In 2.2.2.3, I am closing this one.

**Comment by paulmueller** [comment]
Here is a script that checks for this issue and can optionally fix it automatically.

[check_wrong_medium_shapein_issue3.zip](https://github.com/ZELLMECHANIK-DRESDEN/ShapeIn_Issues/files/6222498/check_wrong_medium_shapein_issue3.zip)

**Comment by paulmueller** [comment]
Shape-In 2.3.0.0 is still affected if the configuration file loaded in Shape-In contains `Buffer_Medium=CellCarrierB` and `Buffer_Medium_ID=0` (i.e. if a configuration file is loaded that was generated by a previously affected Shape-In version).
