### ISSUE TITLE
Shape-In writes empty "setup:chip identifier"

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#4]
Newer versions of Shape-In write "setup:chip identifier" to the .rtdc files, but this is usually an empty string. If no chip identifier is available, I would propose to exclude this attribute.

see also: https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/109

**Comment by phidahl** [comment]
Fixed in release 2.2.2.4. This attribute is for a feature in the future and will not be written as long it was not activated.
