### ISSUE TITLE
Shape-In log is stored as "log" which is not descriptive

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#6]
Shape-In stores its log as "log" in the "log" HDF5-Group. I would propose a more descriptive name, e.g. "Shape-In acquisition".

![image](https://user-images.githubusercontent.com/2853022/114363067-55098480-9b78-11eb-9fd9-7194a59a958d.png)

**Comment by phidahl** [comment]
In the next release (version 2.2.3.0) there will be two datasets in logs:
"logs/shapein-acquisition" holding information about the measurement (content will be extended in the future)
"logs/shapein-warning" holding warnings about the measurement. e.g. if the new background aggregator could not find frames without objects "[WARNING] 12:01:08.187 Forced background image aggregations: 3869 times"
