### ISSUE TITLE
Pump configuration not correct when loading custom settings

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#7]
Shape-In 2.3.0.0

For the use of glass syringes, I saved custom settings with the specific scale length of the syringes:

![shapeIn_pump_settings_not_stored_correctly](https://user-images.githubusercontent.com/75362246/132864660-76958857-81db-45f2-8500-452a54970471.PNG)

I saved the settings via the "Save Settings" button. When loading the settings, however, the checkbox is not checked, although I can see that the scale length was set correctly.

**Comment by phidahl** [comment]
Hi,
thank you for reporting. I'm going to work on this the next day. A fix will be included in the next Release.
